repository:
    private: false
    has_issues: true
    has_wiki: false
    has_downloads: true
    default_branch: master
    allow_squash_merge: false
    allow_merge_commit: true
    allow_rebase_merge: false

# Labels: define labels for Issues and Pull Requests
labels:
    - name: "Dependencies ğŸ“¦"
      color: 0025ff
      description: "Pull requests that update a dependency file"
    - name: "Image ğŸ–¼"
      color: 00ffff
    - name: "HTML ğŸ‘·â€â™€ï¸"
      color: ffffff
    - name: "CSS ğŸ‘©â€ğŸ¨"
      color: b3b3b3
    - name: "JavaScript ğŸ¦"
      color: ffff00
    - name: "Go ğŸ¹"
      color: 00ADD8
    - name: "JSON ğŸ‘¨â€ğŸ’¼"
      color: 00ADD8
    - name: "NEON ğŸ¦¹â€â™‚ï¸"
      color: CE3262
    - name: "MarkDown ğŸ“"
      color: 000000
    - name: "YAML ğŸ„"
      color: ff1aff
    - name: "Templates ğŸŒ²"
      color: 009933
    - name: "Helm â˜¸"
      color: 091C84
    - name: "Tests ğŸ§ª"
      color: ffe6e6
    - name: "Source ğŸ”®"
      color: e6ffe6
    - name: "Configuration âš™"
      color: b3b3cc
    - name: "PHP ğŸ˜"
      color: 8892BF
      description: "Hypertext Pre Processor"
    - name: "Docker ğŸ³"
      color: 0db7ed
      description: "Pull requests that relate to Docker"
    - name: "CI ğŸš§"
      color: ffff00
    - name: "Feature ğŸ—"
      color: 66ff99
    - name: "Documentation ğŸ“š"
      color: 6666ff
    - name: "Security ğŸ•µï¸â€â™€ï¸"
      color: ff0000
    - name: "Hacktoberfest ğŸƒ"
      color: 152347
    - name: "Bug ğŸ"
      color: d73a4a
      description: "Something isn't working"
      oldname: bug
    - name: "Duplicate â™Š"
      color: cfd3d7
      description: "This issue or pull request already exists"
      oldname: duplicate
    - name: "Enhancement âœ¨"
      color: a2eeef
      description: "New feature or request"
      oldname: enhancement
    - name: "Good First Issue"
      color: 7057ff
      description: "Good for newcomers"
      oldname: "good first issue"
    - name: "Help Wanted"
      color: 008672
      description: "Extra attention is needed"
      oldname: "help wanted"
    - name: Invalid
      color: e4e669
      description: "This doesn't seem right"
      oldname: invalid
    - name: "Question â“"
      color: d876e3
      description: "Further information is requested"
      oldname: question
    - name: "Will not be fixed ğŸ›‘"
      color: ffffff
      description: "This will not be worked on"
      oldname: wontfix
    - name: "Sponsor Request â¤ï¸"
      color: fedbf0
      description: "Issue/PR opened by sponsor"
